"""Compiled nitrogen-oxygen enriched galaxy sample from Ji+25: https://arxiv.org/abs/2505.12505"""

points = [
    {
        'name': 'Mrk 996 (high density)',
        'redshift': 0.00544,
        'redshift_err': None,
        'log_N_over_O': -0.13,
        'log_N_over_O_err': 0.28,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 8.38,
        'twelve_plus_log_O_over_H_err': 0.075,
        'age_Myr': 13708.6,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
     {
        'name': 'Mrk 996 (low density)',
        'redshift': 0.00544,
        'redshift_err': None,
        'log_N_over_O': -1.43,
        'log_N_over_O_err': 0.14,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 8.36,
        'twelve_plus_log_O_over_H_err': 0.225,
        'age_Myr': 13708.6,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'Sunburst Arc (LyC)',
        'redshift': 2.37,
        'redshift_err': None,
        'log_N_over_O': -0.21,
        'log_N_over_O_err': 0.105,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 8.03,
        'twelve_plus_log_O_over_H_err': 0.06,
        'age_Myr': 2762.45,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'ID150880',
        'redshift': 4.25,
        'redshift_err': None,
        'log_N_over_O': -0.88,
        'log_N_over_O_err': 0.155,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 8,
        'twelve_plus_log_O_over_H_err': 0.09,
        'age_Myr': 1429.54,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'UNCOVER-45924',
        'redshift': 4.46,
        'redshift_err': None,
        'log_N_over_O': 0.2,
        'log_N_over_O_err': 0.055,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.41,
        'twelve_plus_log_O_over_H_err': 0.26,
        'age_Myr': 1348.13,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'ID1665',
        'redshift': 4.48,
        'redshift_err': None,
        'log_N_over_O': -0.93,
        'log_N_over_O_err': 0.15,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 8.26,
        'twelve_plus_log_O_over_H_err': 0.13,
        'age_Myr': 1340.78,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'ID1746',
        'redshift': 4.57,
        'redshift_err': None,
        'log_N_over_O': -0.85,
        'log_N_over_O_err': 0.145,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.92,
        'twelve_plus_log_O_over_H_err': 0.115,
        'age_Myr': 1308.51,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'ID1477',
        'redshift': 4.63,
        'redshift_err': None,
        'log_N_over_O': -0.62,
        'log_N_over_O_err': 0.105,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.72,
        'twelve_plus_log_O_over_H_err': 0.08,
        'age_Myr': 1287.71,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'ID60001',
        'redshift': 4.69,
        'redshift_err': None,
        'log_N_over_O': -0.76,
        'log_N_over_O_err': 0.03,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.75,
        'twelve_plus_log_O_over_H_err': 0.03,
        'age_Myr': 1267.45,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'EXCELS-121806',
        'redshift': 5.23,
        'redshift_err': None,
        'log_N_over_O': -0.86,
        'log_N_over_O_err': 0.13,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.97,
        'twelve_plus_log_O_over_H_err': 0.045,
        'age_Myr': 1106.58,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'GS_3073',
        'redshift': 5.55,
        'redshift_err': None,
        'log_N_over_O': 0.42,
        'log_N_over_O_err': 0.115,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 8,
        'twelve_plus_log_O_over_H_err': 0.105,
        'age_Myr': 1026.58,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'GS_9422',
        'redshift': 5.94,
        'redshift_err': None,
        'log_N_over_O': -0.85,
        'log_N_over_O_err': None,
        'log_N_over_O_limit': 'upper',
        'twelve_plus_log_O_over_H': 7.59,
        'twelve_plus_log_O_over_H_err': 0.01,
        'age_Myr': 941.337,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'ID397',
        'redshift': 6,
        'redshift_err': None,
        'log_N_over_O': -0.67,
        'log_N_over_O_err': 0.135,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.96,
        'twelve_plus_log_O_over_H_err': 0.09,
        'age_Myr': 929.265,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'RXJ2248-ID',
        'redshift': 6.11,
        'redshift_err': 0.26,
        'log_N_over_O': -0.39,
        'log_N_over_O_err': 0.09,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.43,
        'twelve_plus_log_O_over_H_err': 0.13,
        'age_Myr': 907.791,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'GLASS_150008',
        'redshift': 8.12,
        'redshift_err': 0.005,
        'log_N_over_O': -0.54,
        'log_N_over_O_err': 0.05,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.32,
        'twelve_plus_log_O_over_H_err': 0.1,
        'age_Myr': 25,
        'age_err_Myr': 15,
        'age_method': 'stellar_population (BEAGLE)',
        'sfr_Msun_per_yr': 1.99526,
        'sfr_err_Msun_per_yr': 0.459426,
        'sfr_method': 'log SFR from BEAGLE fits',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Isobe et al. 2025', 'age_sfr': 'Isobe et al. 2025'},
    },
    {
        'name': 'A1703-zd6',
        'redshift': 7.04,
        'redshift_err': 0.32,
        'log_N_over_O': -0.6,
        'log_N_over_O_err': 0.3,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.47,
        'twelve_plus_log_O_over_H_err': 0.19,
        'age_Myr': 754.907,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'GN-z8-LAE',
        'redshift': 8.28,
        'redshift_err': 0.24,
        'log_N_over_O': -0.44,
        'log_N_over_O_err': 0.36,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.85,
        'twelve_plus_log_O_over_H_err': 0.17,
        'age_Myr': 608.646,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'CEERS-1019',
        'redshift': 8.679,
        'redshift_err': 0.008,
        'log_N_over_O': -0.31,
        'log_N_over_O_err': 0.06,
        'log_N_over_O_limit': 'lower',
        'twelve_plus_log_O_over_H': 7.48,
        'twelve_plus_log_O_over_H_err': 0.08,
        'age_Myr': 68,
        'age_err_Myr': 29,
        'age_method': 'stellar_population (BEAGLE)',
        'sfr_Msun_per_yr': 15.1356,
        'sfr_err_Msun_per_yr': 1.74255,
        'sfr_method': 'log SFR from BEAGLE fits',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Isobe et al. 2025', 'age_sfr': 'Isobe et al. 2025'},
    },
    {
        'name': 'GN-z9p4',
        'redshift': 9.38,
        'redshift_err': 0.37,
        'log_N_over_O': -0.59,
        'log_N_over_O_err': 0.24,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.38,
        'twelve_plus_log_O_over_H_err': 0.15,
        'age_Myr': 514.366,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'GS-z9-0',
        'redshift': 9.43,
        'redshift_err': 0.2,
        'log_N_over_O': -0.93,
        'log_N_over_O_err': 0.37,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.49,
        'twelve_plus_log_O_over_H_err': 0.13,
        'age_Myr': 510.665,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'GHZ9',
        'redshift': 10.15,
        'redshift_err': None,
        'log_N_over_O': 0.02,
        'log_N_over_O_err': 0.1,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.19,
        'twelve_plus_log_O_over_H_err': 0.5,
        'age_Myr': 461.914,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'GN-z11',
        'redshift': 10.6,
        'redshift_err': 0.13,
        'log_N_over_O': -0.25,
        'log_N_over_O_err': None,
        'log_N_over_O_limit': 'lower',
        'twelve_plus_log_O_over_H': 7.91,
        'twelve_plus_log_O_over_H_err': 0.07,
        'age_Myr': 18.62, #maximum age of stars from Bunker et al. 2023
        'age_err_Myr': None,
        'age_method': 'SED fitting ',
        'sfr_Msun_per_yr': 18.78,
        'sfr_err_Msun_per_yr': 0.75, #from Bunker et al. 2023
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
    {
        'name': 'GHZ2',
        'redshift': 12.34,
        'redshift_err': 0.25,
        'log_N_over_O': -0.25,
        'log_N_over_O_err': 0.05,
        'log_N_over_O_limit': None,
        'twelve_plus_log_O_over_H': 7.44,
        'twelve_plus_log_O_over_H_err': 0.25,
        'age_Myr': 352.728,
        'age_err_Myr': None,
        'age_method': 'redshift_based (Planck18 cosmic age)',
        'sfr_Msun_per_yr': None,
        'sfr_err_Msun_per_yr': None,
        'sfr_method': 'not_reported',
        'redshift_method': 'spectroscopic',
        'agn_signs': False,
        'sources': {'abundances': 'Ji et al. 2025', 'age_sfr': 'Planck Collaboration 2020'},
    },
]
