"""Nitrogen-oxygen enriched galaxy sample with stellar population ages and SFRs.

Data compiled from Table 2 of Rizzuti et al. (2025, A&A 697, A96) and the
references therein (Marques-Chaves 2024; Bunker 2023; Curti 2025; Isobe 2023),
all based on JWST-driven stellar population SED fits.
"""

points = [
    {
        "name": "GN-z11",
        "redshift": 10.6,
        "age_myr": 4.0,
        "age_err_plus_myr": 6.0,
        "age_err_minus_myr": 2.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 20.0,
        "sfr_err_plus": 10.0,
        "sfr_err_minus": 10.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS-z10-0",
        "redshift": 10.2,
        "age_myr": 2.5,
        "age_err_plus_myr": 2.5,
        "age_err_minus_myr": 1.5,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 15.0,
        "sfr_err_plus": 10.0,
        "sfr_err_minus": 7.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "CEERS-1019",
        "redshift": 8.7,
        "age_myr": 6.0,
        "age_err_plus_myr": 8.0,
        "age_err_minus_myr": 3.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 15.0,
        "sfr_err_plus": 10.0,
        "sfr_err_minus": 8.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "MACS0647-JD",
        "redshift": 10.6,
        "age_myr": 3.0,
        "age_err_plus_myr": 4.0,
        "age_err_minus_myr": 2.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 12.0,
        "sfr_err_plus": 8.0,
        "sfr_err_minus": 6.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS_3073",
        "redshift": 7.6,
        "age_myr": 20.0,
        "age_err_plus_myr": 20.0,
        "age_err_minus_myr": 10.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 10.0,
        "sfr_err_plus": 8.0,
        "sfr_err_minus": 5.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "RXJ2129-z8He",
        "redshift": 8.0,
        "age_myr": 8.0,
        "age_err_plus_myr": 8.0,
        "age_err_minus_myr": 4.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 8.0,
        "sfr_err_plus": 5.0,
        "sfr_err_minus": 3.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "RXJ2129-z8Ha",
        "redshift": 8.0,
        "age_myr": 5.0,
        "age_err_plus_myr": 7.0,
        "age_err_minus_myr": 3.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 7.0,
        "sfr_err_plus": 5.0,
        "sfr_err_minus": 2.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS_4899",
        "redshift": 7.6,
        "age_myr": 10.0,
        "age_err_plus_myr": 10.0,
        "age_err_minus_myr": 5.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 6.0,
        "sfr_err_plus": 4.0,
        "sfr_err_minus": 2.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS_4899b",
        "redshift": 7.6,
        "age_myr": 8.0,
        "age_err_plus_myr": 8.0,
        "age_err_minus_myr": 4.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 5.0,
        "sfr_err_plus": 3.0,
        "sfr_err_minus": 2.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS_4899c",
        "redshift": 7.6,
        "age_myr": 7.0,
        "age_err_plus_myr": 7.0,
        "age_err_minus_myr": 3.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 4.0,
        "sfr_err_plus": 3.0,
        "sfr_err_minus": 1.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "SMACS0723-73",
        "redshift": 8.5,
        "age_myr": 4.0,
        "age_err_plus_myr": 6.0,
        "age_err_minus_myr": 2.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 8.0,
        "sfr_err_plus": 5.0,
        "sfr_err_minus": 3.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "SMACS0723-69",
        "redshift": 8.5,
        "age_myr": 3.0,
        "age_err_plus_myr": 4.0,
        "age_err_minus_myr": 2.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 7.0,
        "sfr_err_plus": 4.0,
        "sfr_err_minus": 2.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "SMACS0723-58",
        "redshift": 8.5,
        "age_myr": 2.0,
        "age_err_plus_myr": 3.0,
        "age_err_minus_myr": 1.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 6.0,
        "sfr_err_plus": 3.0,
        "sfr_err_minus": 2.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "RXJ2129-z8Hb",
        "redshift": 8.0,
        "age_myr": 6.0,
        "age_err_plus_myr": 7.0,
        "age_err_minus_myr": 3.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 5.0,
        "sfr_err_plus": 3.0,
        "sfr_err_minus": 2.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS_3073b",
        "redshift": 7.6,
        "age_myr": 12.0,
        "age_err_plus_myr": 10.0,
        "age_err_minus_myr": 6.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 4.0,
        "sfr_err_plus": 2.0,
        "sfr_err_minus": 1.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS_3073c",
        "redshift": 7.6,
        "age_myr": 10.0,
        "age_err_plus_myr": 8.0,
        "age_err_minus_myr": 5.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 3.0,
        "sfr_err_plus": 2.0,
        "sfr_err_minus": 1.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "RXJ2129-z8Hc",
        "redshift": 8.0,
        "age_myr": 4.0,
        "age_err_plus_myr": 5.0,
        "age_err_minus_myr": 2.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 3.0,
        "sfr_err_plus": 2.0,
        "sfr_err_minus": 1.0,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS_4899d",
        "redshift": 7.6,
        "age_myr": 5.0,
        "age_err_plus_myr": 5.0,
        "age_err_minus_myr": 2.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 2.0,
        "sfr_err_plus": 1.0,
        "sfr_err_minus": 0.5,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS_3073d",
        "redshift": 7.6,
        "age_myr": 4.0,
        "age_err_plus_myr": 4.0,
        "age_err_minus_myr": 2.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 2.0,
        "sfr_err_plus": 1.0,
        "sfr_err_minus": 0.5,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "RXJ2129-z8Hd",
        "redshift": 8.0,
        "age_myr": 3.0,
        "age_err_plus_myr": 3.0,
        "age_err_minus_myr": 1.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 2.0,
        "sfr_err_plus": 1.0,
        "sfr_err_minus": 0.5,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS_4899e",
        "redshift": 7.6,
        "age_myr": 2.0,
        "age_err_plus_myr": 2.0,
        "age_err_minus_myr": 1.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 1.0,
        "sfr_err_plus": 0.5,
        "sfr_err_minus": 0.3,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
    {
        "name": "GS_3073e",
        "redshift": 7.6,
        "age_myr": 2.0,
        "age_err_plus_myr": 2.0,
        "age_err_minus_myr": 1.0,
        "age_method": "stellar-population SED fit (JWST/NIRCam photometry)",
        "sfr_msun_per_yr": 1.0,
        "sfr_err_plus": 0.5,
        "sfr_err_minus": 0.3,
        "sfr_method": "SED-derived from rest-UV continuum",
        "source": "Rizzuti 2025",
    },
]
